version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/teaching.ss23prse.smartroom.team3

    steps:
      - checkout

      # Backend (Spring Boot)
      - run:
          name: Build and test backend
          command: |
            cd smartroom_backend
            chmod +x mvnw
            ./mvnw clean install

      # Frontend (Angular)
      - run:
          name: Build and test frontend
          command: |
            cd smartroom-frontend
            npm install
            ng test --watch=false --browsers=ChromeHeadless

workflows:
  version: 2
  build:
    jobs:
      - build
